name = "HarnessingChaos"
uuid = "28c4900a-4950-4990-8e73-e6a6f348ac36"
authors = ["Debarchito Nath <dev.debarchito.nath@protonmail.com>"]
version = "0.1.0"

[deps]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[compat]
JuliaFormatter = "1.0.62"
Pluto = "0.20.4"
